
# App Info
spring.application.name=schoolManagementDB

# PostgreSQL DB Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Timezone Handling (Optional but Recommended)
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Enable automatic timestamp auditing (CreatedDate / LastModifiedDate)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
